### ISSUE TITLE
Events from server  do not reach client

### ISSUE THREAD

**Issue by minchenkov** [lihaoyi/SprayWebSockets#3] opened 2013-11-18 13:36 UTC
I'm using SprayWebSockets to communicate with browser. Everything works on the local environment, when server and client on the same machine. But on the production environment there is a strange behavior: sometimes events from server doesn't reach the client (Google Chrome). Events size and count is the same as on the local environment. After this behavior socket stops working and doesn't send any data from server to connected socket client. At the same time there are log messages for each unreached event:

```
event pipeline: dropped CommandFailed(Write(ByteString....))
```

I'm using latest SprayWebSockets.

**Comment by lihaoyi** [comment] 2013-11-18 18:15
I've found this problem too. It turns out that the problem is me not handling backpressure (see https://groups.google.com/forum/#!topic/spray-user/A-yeLmj_hSw) which causes things to be silently dropped if you send messages too fast. The tests weren't triggering it because they didn't send data fast enough. 

I'm working on a fix.

**Comment by lihaoyi** [comment] 2013-11-23 17:34
After poking around a while, I'm pretty stumped on what the correct solution should be. Hopefully when spray 1.2 stabilizes the approach/docs around backpressure will stabilize and I'll take another pass at it.

If anyone else has any ideas/suggestions/patches, I'll be glad to hear them =)

**Comment by minchenkov** [comment] 2013-11-25 14:50
Maybe there are techniques or workarounds to avoid backpressure?

**Comment by shengc** [comment] 2013-12-03 13:11
Akka io ack mode is documented here:
http://doc.akka.io/docs/akka/2.2.0-RC1/scala/io-tcp.html#Throttling_Reads_and_Writes
Is it possible to integrate that as a temporary solution for the back pressure as suggested in the google group thread?

**Comment by lihaoyi** [comment] 2013-12-03 18:03
Yeah, it is, and in fact Spray 1.2 Final has just been released! I'll take a look at this again when I have the time, and as always patches are welcome =)

**Comment by lihaoyi** [comment] 2013-12-10 05:43
This should be fixed as of https://github.com/lihaoyi/SprayWebSockets/commit/7390085b91e19fdd1963b966f9cad11f518ee3aa. At the very least, at the rate I was sending things, I wasn't having any problems, and `BackPressureHandling` was doing the right thing in buffering up the `Tcp.Write`s appropriately.

Let me know if anyone's still having issues.

**Closed as completed by lihaoyi** 2013-12-10 05:43 UTC
